# Generated by Django 5.0 on 2023-12-13 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_contact_us_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Contact_us',
        ),
    ]
